name: assets-api
services:
  assets-api:
    container_name: assets-api
    image: ghcr.io/claudiusayadi/assets-api:latest
    restart: unless-stopped
    volumes:
      - ./assets:/assets
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.assets-api.rule=Host(`assets.dovely.tech`)'
      - 'traefik.http.routers.assets-api.entrypoints=live'
      - 'traefik.http.routers.assets-api.tls=true'
      - 'traefik.http.services.assets-api.loadbalancer.server.port=3000'
    networks:
      - proxy
